export const AppError = {
  USER_EXIST: 'User with this email exist',
  USER_NOT_FOUND: 'User with this email not found',
  USER_WRONG_PASSWORD: 'Your password is wrong',
  ROLE_EXIST: 'This role already exist',
  COMPANY_EXIST: 'This company already exist',
  COMPANY_NOT_FOUND: 'This company not found',
  PAGE_EXIST: 'This page already exist',
  PAGE_NOT_FOUND: 'This page not found',
  MENU_FOUND: 'Menu already exist',
  MENU_NOT_FOUND: 'Menu not found',
  CATEGORY_FOUND: 'Category already exist',
  CATEGORY_NOT_FOUND: 'Category not found',
  SEARCH_HISTORY_FOUND: 'Search history already exist',
  SEARCH_HISTORY_NOT_FOUND: 'Search history not found',
  PRODUCT_FOUND: 'Product already exist',
  PRODUCT_NOT_FOUND: 'Product not found',
  TAG_FOUND: 'Tag already exist',
  TAG_NOT_FOUND: 'Tag not found',
  PRODUCT_TYPE_FOUND: 'Product type exist',
  PRODUCT_TYPE_NOT_FOUND: 'Product type not found',
  PROPERTY_NAME_FOUND: 'Property name exist',
  PROPERTY_NAME_NOT_FOUND: 'Property name not found',
  PROPERTY_VALUE_FOUND: 'Property value exist',
  PROPERTY_VALUE_NOT_FOUND: 'Property value not found',
  PASSWORD_WRONG: 'Password wrong',
  MEDIA_TYPE_FOUND: 'Media type exist',
  MEDIA_TYPE_NOT_FOUND: 'Media type not found',
  LEAD_STATUS_FOUND: 'Lead status exist',
  LEAD_STATUS_NOT_FOUND: 'Lead status not found',
  LEAD_TYPE_FOUND: 'Lead type exist',
  LEAD_TYPE_NOT_FOUND: 'Lead type not found',
};
